-- Insert product types if not exists, ignore if exists
INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    1,
    'Electronics'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 1 OR NAME = 'Electronics');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    2,
    'Clothing'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 2 OR NAME = 'Clothing');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    3,
    'Food'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 3 OR NAME = 'Food');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    4,
    'Furniture'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 4 OR NAME = 'Furniture');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    5,
    'Books'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 5 OR NAME = 'Books');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    6,
    'Toys'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 6 OR NAME = 'Toys');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    7,
    'Sports'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 7 OR NAME = 'Sports');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    8,
    'Health'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 8 OR NAME = 'Health');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    9,
    'Beauty'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 9 OR NAME = 'Beauty');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    10,
    'Automotive'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 10 OR NAME = 'Automotive');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    11,
    'Home'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 11 OR NAME = 'Home');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    12,
    'Garden'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 12 OR NAME = 'Garden');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    13,
    'Industrial'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 13 OR NAME = 'Industrial');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    14,
    'Movies'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 14 OR NAME = 'Movies');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    15,
    'Music'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 15 OR NAME = 'Music');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    16,
    'Pet Supplies'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 16 OR NAME = 'Pet Supplies');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    17,
    'Shoes'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 17 OR NAME = 'Shoes');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    18,
    'Software'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 18 OR NAME = 'Software');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    19,
    'Tools'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 19 OR NAME = 'Tools');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    20,
    'Toys'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 20 OR NAME = 'Toys');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    21,
    'Video Games'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 21 OR NAME = 'Video Games');

INSERT INTO
    PRODUCT_TYPES (ID, NAME)
SELECT
    22,
    'Other'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_TYPES WHERE ID = 22 OR NAME = 'Other');

-- Insert product brands if not exists, ignore if exists
INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    1,
    'Apple'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 1 OR NAME = 'Apple');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    2,
    'Samsung'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 2 OR NAME = 'Samsung');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    3,
    'Sony'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 3 OR NAME = 'Sony');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    4,
    'Microsoft'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 4 OR NAME = 'Microsoft');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    5,
    'LG'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 5 OR NAME = 'LG');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    6,
    'HTC'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 6 OR NAME = 'HTC');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    7,
    'Nokia'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 7 OR NAME = 'Nokia');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    8,
    'Motorola'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 8 OR NAME = 'Motorola');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    9,
    'Blackberry'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 9 OR NAME = 'Blackberry');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    10,
    'Dell'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 10 OR NAME = 'Dell');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    11,
    'HP'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 11 OR NAME = 'HP');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    12,
    'Lenovo'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 12 OR NAME = 'Lenovo');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    13,
    'Acer'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 13 OR NAME = 'Acer');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    14,
    'Asus'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 14 OR NAME = 'Asus');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    15,
    'Toshiba'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 15 OR NAME = 'Toshiba');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    16,
    'Canon'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 16 OR NAME = 'Canon');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    17,
    'Nikon'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 17 OR NAME = 'Nikon');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    18,
    'Panasonic'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 18 OR NAME = 'Panasonic');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    19,
    'Sony'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 19 OR NAME = 'Sony');

INSERT INTO
    PRODUCT_BRANDS (ID, NAME)
SELECT
    20,
    'Philips'
FROM
    DUAL
WHERE
    NOT EXISTS (SELECT 1 FROM PRODUCT_BRANDS WHERE ID = 20 OR NAME = 'Philips');
